name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: |
        cd packages/common
        npm ci
        npm run build
        cd ../../apps/api
        npm ci
    
    - name: Install libssl3
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl3

    - name: Set up Firebase service account
      run: |
        mkdir -p apps/api/config
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > apps/api/config/golf-app-27b4b-firebase-adminsdk-fbsvc-8dbba234ee.json
    
    - name: Run tests
      run: |
        cd apps/api
        npm test
      env:
        NODE_ENV: test
        JWT_SECRET: test-jwt-secret-key-min-32-chars-long
        JWT_EXPIRES_IN: 1h
        GOOGLE_CLIENT_ID: test-google-client-id
        GOOGLE_CLIENT_SECRET: test-google-client-secret
        APPLE_CLIENT_ID: test-apple-client-id
        APPLE_TEAM_ID: test-apple-team-id
        APPLE_KEY_ID: test-apple-key-id
        APPLE_PRIVATE_KEY: test-apple-private-key
        AUTH_CALLBACK_URL: http://localhost:3000/auth/callback 